# -*- coding: utf-8 -*-
"""So_codigo_Automacao_Tarefa_IA_LLM_Gemini_Relatorio_Diario_Campanhas_Marketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4KvTzvJaKbxsXdsi9R--N10Z9f5P_8L
"""

#Instalar a biblioteca do Gemini
!pip install -q google-genai

# descobrir quais modelos estão disponíveis na conta
from google import genai

client = genai.Client(api_key="MINHA-API-KEY-GEMINI")

for modelo in client.models.list():
    print(modelo.name)

# testando para ver se o modelo está rodando
resposta = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Olá! Me explique em 2 linhas o que é CPA no marketing digital."
)

print(resposta.text)

# checagem para ver como estão os dados (dá para aumenta o break até, por exemplo, i>10, para ver melhor os dados)
with open("gads-4-7-maio-2026.csv", "r", encoding="latin1") as f:
    for i, linha in enumerate(f):
        print(f"Linha {i}: {linha[:100]}")
        if i > 1:
            break

#Vou importar o pandas porque vou começar a precisar fazer um tratamento nos dados.

import pandas as pd

df = pd.read_csv("gads-4-7-maio-2026.csv", encoding="latin1", skiprows=2) # vai dar certo porque usei skiprows=2, que manda o pandas pular as 2 primeiras linhas antes de começar a ler.
df.head(0) # Vou printar só o cabeçalho para evitar mostrar dados que possam ser sensíveis.

print(df.columns.tolist()) # Notemos que o arquivo tem 43 colunas, vamos usar só as necessárias. Listando as colunas abaixo:

# Vou mudar o nome da coluna OrÃ§amento e Tipo de OrÃ§amento por Orçamento e Tipo de Orçamento, respectivamente,, porque, como são variáveis que vou usar, quero seguir com elas certinhas.

df = df.rename(columns={"OrÃ§amento": "Orçamento", "Tipo de orÃ§amento": "Tipo de orçamento"})
print(df.columns.tolist())

#Vou selecionar só as colunas de Dia, Campanha, Orçamento, Tipo de Orçamento e Custo, pois quero uma avaliação sobre o seguinte problema.

colunas = ["Dia", "Campanha", "Orçamento", "Custo", "Tipo de orçamento", "Custo / conv."]
df_analise = df[colunas].copy()
df_analise = df_analise[df_analise["Campanha"].notna()]
df_analise = df_analise[df_analise["Dia"].notna()]

df_analise.head(0)

# Trocando o encoding da palavra Diário antes de enviar para o Gemini.

df_analise["Tipo de orçamento"] = df_analise["Tipo de orçamento"].str.replace("DiÃ¡rio", "Diário").str.replace("Total da campanha", "Total da campanha")

print(df_analise["Tipo de orçamento"].unique())

df_analise.head(0)

# Prompt para análise em linguagem natural
# O erro que pode dar é se sobrecarga no Gemini.

tabela_texto = df_analise.to_string(index=False)

prompt = f"""
Você é um analista de mídia sênior especializado em Google Ads.

Contexto: Os dados abaixo cobrem os dias 4 até 7 de maio.
No dia 3 de maio foram feitos ajustes de orçamento nas campanhas.
Hoje ainda é dia 7, os dados de custo desse dia ainda são de hoje.
Análise dos resultados entre os dias 4 a 7 vão ser
relaventes para sugerir possíveis ajustes nas campanhas a serem feitos hoje. Também leve em consideração o Custo/conv.

IMPORTANTE sobre o campo "Tipo de orçamento":
- "Diário": o valor de Orçamento representa o limite diário da campanha.
  Compare diretamente Orçamento vs Custo por dia.
- "Total da campanha":  ignore para fins de comparação direta.
- "--":  ignore para fins de comparação direta.

Analise:
Quais campanhas é mais recomendado fazer ajuste de aumento ou diminuição de orçamento?


DADOS:
{tabela_texto}
"""

resposta = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt,
    config={"temperature": 0.1} # vou adicionar esse parâmetro para controlar o quanto o LLM 'cria' resposta vs o quanto 'segue um padrão'
)

print(resposta.text)

# salvando o elatório automaticamente num arquivo .txt, para que no futuro o script faça tudo sozinho e entregue o resultado salvo sem precisar copiar nada

from datetime import date

nome_arquivo = f"relatorio_{date.today()}.txt"

with open(nome_arquivo, "w", encoding="utf-8") as f:
    f.write(resposta.text)

print(f"Relatório salvo como: {nome_arquivo}")

# Script para enviar o relatório por email
#Será necessário configurar a senha de app do Gmail. Isso é uma senha especial criada só para o script usar nesse contexto


import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import date

EMAIL_REMETENTE = "meuemail@gmail.com"
EMAIL_SENHA     = "senha-de-app-do-gmail"
EMAIL_DESTINO   = ["email-1@gmail.com", "email-2@gmail.com"]

msg = MIMEMultipart()
msg["From"]    = EMAIL_REMETENTE
msg["To"]      = ", ".join(EMAIL_DESTINO)
msg["Subject"] = f"Campanhas (Análise em Linguagem Natural) | {date.today()}"

corpo = "Segue em anexo o relatório automático de análise de campanhas gerado pela API do Gemini."
msg.attach(MIMEText(corpo, "plain"))

with open(nome_arquivo, "rb") as f:
    anexo = MIMEBase("application", "octet-stream")
    anexo.set_payload(f.read())
    encoders.encode_base64(anexo)
    anexo.add_header("Content-Disposition", f"attachment; filename={nome_arquivo}")
    msg.attach(anexo)

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as servidor:
    servidor.login(EMAIL_REMETENTE, EMAIL_SENHA)
    servidor.sendmail(EMAIL_REMETENTE, EMAIL_DESTINO, msg.as_string())

print(f"✅ Email enviado para: {EMAIL_DESTINO}")